# @package _group_

# AGIFORMER Base Hardware Configuration
# Default hardware settings for AGIFORMER

# Device Settings
device: auto  # auto, cuda, cpu
gpu_ids: [0]
num_gpus: 1

# Memory Management
memory_fraction: 0.9
allow_growth: true
pytorch_cuda_alloc_conf: expandable_segments

# Distributed Training
distributed: false
backend: nccl
init_method: env

# Performance
cudnn_benchmark: true
cudnn_deterministic: false
num_threads: 4
