# Developer: inkbytefo
# Modified: 2025-11-06

# @package _group_

# AGIFORMER CPU Hardware Configuration
# Settings optimized for CPU training

defaults:
  - _self_

# Device settings
device: cpu
num_threads: 4

# Memory and performance settings
use_amp: false
num_workers: 2
pin_memory: false
persistent_workers: false

# Batch size optimization for CPU
training:
  batch_size: 4
  gradient_accumulation_steps: 8
  use_gradient_checkpointing: false

# CPU-optimized model settings
model:
  d_model: 256  # Reduced for CPU
  n_layers: 4   # Reduced for CPU
  n_heads: 4    # Reduced for CPU
  d_ff: 1024    # Reduced for CPU
  max_seq_len: 256  # Reduced for CPU
  use_memory: false
  use_introspection: false
  use_multimodal: false
  use_linear_attention: true  # Enable for CPU efficiency