
# Logging and experiment tracking configuration

# Console logging level used by train.main()(train.py:243)
# One of: DEBUG, INFO, WARNING, ERROR, CRITICAL
console_level: INFO

# W&B integration toggle
use_wandb: false

# Default W&B project and metadata (used if use_wandb: true)
wandb_project: agiformer
wandb_tags:
  - agiformer
  - hydra
  - training
wandb_notes: "AGIFORMER hydra-managed training run"
