# AGIFORMER Base Model Configuration
# Common architectural settings shared across all model variants

# Architecture
vocab_size: 256
d_model: 512
n_layers: 8
n_heads: 8
d_ff: 2048

# Mixture of Experts
n_experts: 2
expert_types: ["language", "logic"]

# Memory System
memory_size: 1000
max_seq_len: 512

# Regularization
dropout: 0.1

# Feature flags - Override in variant configs
use_linear_attention: false
use_memory: false
use_introspection: false
use_multimodal: false
