# @package _group_

# AGIFORMER Base Model Configuration
# Default model settings for AGIFORMER

# Architecture
vocab_size: 256
d_model: 512
n_layers: 8
n_heads: 8
d_ff: 2048

# Mixture of Experts
n_experts: 2
expert_types: ["language", "logic"]

# Memory System
memory_size: 1000
max_seq_len: 512

# Features
use_linear_attention: false
use_memory: true
use_introspection: true
use_multimodal: false

# Regularization
dropout: 0.1
