## Developer: inkbytefo
## Modified: 2025-11-07
# @package _group_

# Varsayılan model parametreleri
d_model: 512
n_layers: 8
n_heads: 8
d_ff: 2048
n_experts: 1
expert_types: ["language"]
memory_size: 0
max_seq_len: 512
dropout: 0.1
use_linear_attention: false
use_memory: false
use_introspection: false
use_multimodal: false
use_agglutinative_attention: false
tokenizer_path: "tokenizer/morphopiece.model"

# LanguageExpert için varsayılan ayarlar
language_expert:
  use_morpho_semantic_embeddings: false